[package]
name = "docker-mdbook-ja"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.28"
mdbook-linkcheck = "0.7.7"
mdbook-mermaid = "0.12.6"
