#!/bin/bash -eu

if [ $# -ne 1 ]; then
    echo "Usage: $0 <package_name> <package_version>" >&2
    exit 1
fi

set -x
set -o pipefail

package="$1"
version="$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].dependencies[] | select (.name == "'"${package}"'").req' | sed 's/^\^//')"

echo "Installing ${package} ${version}..." >&2

cargo install "${package}" --version "${version}" --root /build
