#!/bin/sh -eu

if [ $# -ne 2 ]; then
    echo "Usage: $0 <package_name> <package_version>"
    exit 1
fi

set -x

package="$1"
version="$2"
arch="$(uname -m)"
binary_url=""

case "${package}" in
mdbook) ;;
mdbook-mermaid)
    case "${arch}" in
    x86_64) binary_url="https://github.com/badboy/mdbook-mermaid/releases/download/v${version}/mdbook-mermaid-v${version}-x86_64-unknown-linux-musl.tar.gz" ;;
    esac
    ;;
esac

if [ -z "${binary_url}" ]; then
    cargo install "${package}" --version "${version}" --root /build
else
    curl -L "${binary_url}" | tar -xzv -C ./bin/
fi
