#!/bin/bash -eu

if [ $# -ne 1 ]; then
    echo "Usage: $0 <package_name> <package_version>" >&2
    exit 1
fi

set -x
set -o pipefail

package="$1"
arch="$(uname -m)"
binary_url=""
extract=""

version="$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].dependencies[] | select (.name == "'"${package}"'").req' | sed 's/^\^//')"
echo "Installing ${package} ${version}..." >&2

case "${package}" in
mdbook)
    case "${arch}" in
    x86_64)
        binary_url="https://github.com/rust-lang/mdBook/releases/download/v${version}/mdbook-v${version}-${arch}-unknown-linux-gnu.tar.gz"
        extract="mdbook"
        ;;
    esac
    ;;
mdbook-mermaid)
    case "${arch}" in
    x86_64)
        binary_url="https://github.com/badboy/mdbook-mermaid/releases/download/v${version}/mdbook-mermaid-v${version}-${arch}-unknown-linux-gnu.tar.gz"
        extract="mdbook-mermaid"
        ;;
    esac
    ;;
mdbook-linkcheck)
    case "${arch}" in
    x86_64)
        binary_url="https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v${version}/mdbook-linkcheck.${arch}-unknown-linux-gnu.zip"
        extract="mdbook-linkcheck"
        ;;
    esac
    ;;
mdbook-pdf)
    case "${arch}" in
    x86_64)
        binary_url="https://github.com/HollowMan6/mdbook-pdf/releases/download/v${version}/mdbook-pdf-v${version}-${arch}-unknown-linux-gnu"
        extract="mdbook-pdf"
        ;;
    esac
    ;;
esac

case "${binary_url}" in
*.tar.gz)
    curl -L "${binary_url}" >binary.tar.gz
    tar -xzvf binary.tar.gz
    cp "${extract}" /build/bin/
    chmod +x /build/bin/"${extract}"
    ;;
*.zip)
    curl -L "${binary_url}" >binary.zip
    unzip binary.zip
    cp "${extract}" /build/bin/
    chmod +x /build/bin/"${extract}"
    ;;
"")
    cargo install "${package}" --version "${version}" --root /build
    ;;
*)
    curl -L "${binary_url}" >"${extract}"
    cp "${extract}" /build/bin
    chmod +x /build/bin/"${extract}"
    ;;
esac
