name: Lint

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/hadolint/hadolint-action
      - name: Lint Dockerflle
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
